"""add is_detected to cameras

Revision ID: 10e620de7c3a
Revises: b085befd0ee6
Create Date: 2026-03-08 03:43:44.459555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10e620de7c3a'
down_revision: Union[str, Sequence[str], None] = 'b085befd0ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('is_detected', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'is_detected')
    # ### end Alembic commands ###
