import { useState } from "react";
import { acknowledgeAlert } from "../api/incidentApi";

// ─────────────────────────────────────────────
// WHAT IS A COMPONENT?
// A component is just a function that returns HTML-like code (called JSX).
// React uses components like LEGO bricks — you build small pieces
// and combine them into bigger ones.
//
// This component receives an "alert" object as a "prop".
// Props are like function arguments — data passed in from the parent.
// ─────────────────────────────────────────────

// SEVERITY CONFIG: maps severity level → color + label
// This makes it easy to add new severity types later.
const SEVERITY = {
  HIGH:   { bg: "bg-red-500/20",    border: "border-red-500",    text: "text-red-400",    dot: "bg-red-500",    label: "HIGH" },
  MEDIUM: { bg: "bg-amber-500/20",  border: "border-amber-500",  text: "text-amber-400",  dot: "bg-amber-500",  label: "MEDIUM" },
  LOW:    { bg: "bg-blue-500/20",   border: "border-blue-500",   text: "text-blue-400",   dot: "bg-blue-500",   label: "LOW" },
};

export default function AlertCard({ alert, onAcknowledge }) {
  // acknowledged = has this alert been marked as handled?
  // useState(false) means it starts as false (not acknowledged).
  const [acknowledged, setAcknowledged] = useState(alert.acknowledged || false);
  const [loading, setLoading] = useState(false);

  // Look up the style config for this alert's severity.
  // Falls back to MEDIUM if the severity is unknown.
  const sev = SEVERITY[alert.severity] || SEVERITY.MEDIUM;

  // Format the timestamp into a readable time string.
  // e.g. "2025-03-06T14:32:00Z" → "2:32:00 PM"
  const time = new Date(alert.timestamp).toLocaleTimeString();
  const date = new Date(alert.timestamp).toLocaleDateString();

  // This function runs when staff clicks "Acknowledge".
  async function handleAcknowledge() {
    setLoading(true);
    try {
      await acknowledgeAlert(alert.id); // calls FastAPI
      setAcknowledged(true);
      if (onAcknowledge) onAcknowledge(alert.id); // tells parent component
    } catch (err) {
      console.error("Failed to acknowledge:", err);
    } finally {
      setLoading(false);
    }
  }

  return (
    // The outer div is the card container.
    // Template literals (backticks) let us insert variables into class names.
    <div className={`
      rounded-xl border p-4 mb-3 transition-all duration-300
      ${sev.bg} ${sev.border}
      ${acknowledged ? "opacity-50" : "opacity-100"}
    `}>

      {/* TOP ROW: severity badge + camera + time */}
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          {/* Pulsing dot — only pulses if HIGH severity and not acknowledged */}
          <span className={`
            w-2.5 h-2.5 rounded-full ${sev.dot}
            ${alert.severity === "HIGH" && !acknowledged ? "animate-pulse" : ""}
          `}/>
          {/* Severity badge */}
          <span className={`text-xs font-bold tracking-widest ${sev.text}`}>
            {sev.label}
          </span>
        </div>
        <span className="text-xs text-slate-400 font-mono">{date} {time}</span>
      </div>

      {/* CAMERA + LOCATION INFO */}
      <div className="flex gap-4 mb-3">
        {/* Snapshot image from the camera */}
        {alert.snapshot_url && (
          <img
            src={alert.snapshot_url}
            alt="Incident snapshot"
            className="w-24 h-16 object-cover rounded-lg border border-slate-600"
            // If image fails to load, hide it
            onError={(e) => e.target.style.display = "none"}
          />
        )}
        <div>
          <p className="text-white font-semibold text-sm">{alert.location}</p>
          <p className="text-slate-400 text-xs font-mono mt-0.5">
            Camera ID: {alert.camera_id}
          </p>
        </div>
      </div>

      {/* GEMINI AI SUMMARY */}
      {/* This is the text generated by Gemini describing what happened */}
      <div className="bg-slate-800/60 rounded-lg p-3 mb-3 border border-slate-700">
        <p className="text-xs text-slate-400 uppercase tracking-wider mb-1 font-semibold">
          AI Summary
        </p>
        <p className="text-slate-200 text-sm leading-relaxed">
          {alert.summary || "Generating summary..."}
        </p>
      </div>

      {/* ACKNOWLEDGE BUTTON */}
      {/* Only shows if not yet acknowledged */}
      {!acknowledged ? (
        <button
          onClick={handleAcknowledge}
          disabled={loading}
          className="w-full py-2 rounded-lg text-xs font-bold tracking-wider uppercase
            bg-slate-700 hover:bg-slate-600 text-slate-200
            border border-slate-600 hover:border-slate-500
            transition-all duration-200 disabled:opacity-50"
        >
          {loading ? "Acknowledging..." : "✓ Acknowledge Alert"}
        </button>
      ) : (
        <p className="text-center text-xs text-slate-500 font-mono">✓ Acknowledged</p>
      )}
    </div>
  );
}
