"""message

Revision ID: 652485be41c8
Revises: 10e620de7c3a
Create Date: 2026-03-08 04:41:07.060242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '652485be41c8'
down_revision: Union[str, Sequence[str], None] = '10e620de7c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('last_detected_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('cameras', 'is_detected')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('is_detected', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('cameras', 'last_detected_at')
    # ### end Alembic commands ###
